name: Main CI

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    environment: tests

  env:
    MAIL_URL: ${{ vars.MAIN_URL }}

  steps:
    - uses: action/checkout@v3

    - name: Set up Python
      uses: action/setup-python@v3
      with:
        python-version: 3.11.4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install project
      run: |
        poetry install

    - name: Run Tests
      run: |
        poetry run pytest
    
    - name: Run mypy
      run: |
        poetry run mypy ./

    - name: Run pylint
      run: |
        poetry run pylint ./evrone_fastapi


